In [78]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/imdb-dataset-of-50k-movie-reviews/IMDB Dataset.csv

# **How to Handle Textual Data in NLP**

#### In this notebook, I aim to provide insights into "How to Handle Textual Data in NLP". I will cover two major aspects:

1. Text Preprocessing: I will demonstrate how to preprocess textual data using a real-world dataset, specifically the "IMDB-Movies" dataset. My primary focus is to simplify and illustrate text preprocessing techniques. However, if you encounter any difficulties, please feel free to comment, and I will do my best to address them.

2. Text Representation: Text representation involves converting textual data into numerical format. I will discuss some of the most important techniques for handling textual data in machine learning, including:

#### One-Hot Encoding (OHE)
#### Bag of Words

# **Text Preprocessing**

# **Basis Libraries**

In [79]:
# for punctuation
import string
import pandas as pd

# remove stop-words
from nltk.corpus import stopwords

# import regular expression
import re

# Import PorterStemmer from NLTK Library
from nltk.stem.porter import PorterStemmer
# Lemmatization
from nltk.stem import WordNetLemmatizer
# Tokenization
from nltk.tokenize import word_tokenize
# Imporr Ohe 
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [80]:
df = pd.read_csv("/kaggle/input/imdb-dataset-of-50k-movie-reviews/IMDB Dataset.csv")
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [81]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

# **Basis Text Preprocessing**

#  **LowerCasing**

In [82]:
df['review'] = df['review'].str.lower()
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. <br /><br />the...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

# **upperCasing**

In [83]:
df['review'] = df['review'].str.upper()
df.head()

                                              review sentiment
0  ONE OF THE OTHER REVIEWERS HAS MENTIONED THAT ...  positive
1  A WONDERFUL LITTLE PRODUCTION. <BR /><BR />THE...  positive
2  I THOUGHT THIS WAS A WONDERFUL WAY TO SPEND TI...  positive
3  BASICALLY THERE'S A FAMILY WHERE A LITTLE BOY ...  negative
4  PETTER MATTEI'S "LOVE IN THE TIME OF MONEY" IS...  positive

# **Removing Punctuations**

In [84]:
# Removing Punctuations
df.review = df.review.replace(string.punctuation, '')
df.head()

                                              review sentiment
0  ONE OF THE OTHER REVIEWERS HAS MENTIONED THAT ...  positive
1  A WONDERFUL LITTLE PRODUCTION. <BR /><BR />THE...  positive
2  I THOUGHT THIS WAS A WONDERFUL WAY TO SPEND TI...  positive
3  BASICALLY THERE'S A FAMILY WHERE A LITTLE BOY ...  negative
4  PETTER MATTEI'S "LOVE IN THE TIME OF MONEY" IS...  positive

# **Remove Stopword**

In [85]:
import nltk
from nltk.corpus import stopwords
# Download stopwords if not already downloaded
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /usr/share/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

# **lowercase word**

In [86]:
df['review'] = df['review'].str.lower()
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. <br /><br />the...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

In [87]:
# Intilize Stopwords
stop_words = stopwords.words('english')

# Apply Stopwords
df['review'] = df['review'].apply(lambda x : ' '.join([word for word in x.split() if word not in (stop_words)]))
# Head 
df.head()

                                              review sentiment
0  one reviewers mentioned watching 1 oz episode ...  positive
1  wonderful little production. <br /><br />the f...  positive
2  thought wonderful way spend time hot summer we...  positive
3  basically there's family little boy (jake) thi...  negative
4  petter mattei's "love time money" visually stu...  positive

# **Removing HTMl Tags**

In [88]:
from bs4 import BeautifulSoup

# Function to remove HTML tags
def remove_html_tags(text):
    soup = BeautifulSoup(text, "html.parser")
    return soup.get_text()

# Applying the function to the 'review' column
df['review'] = df['review'].apply(remove_html_tags)
df.head()

/tmp/ipykernel_33/384061778.py:5: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  soup = BeautifulSoup(text, "html.parser")

                                              review sentiment
0  one reviewers mentioned watching 1 oz episode ...  positive
1  wonderful little production. the filming techn...  positive
2  thought wonderful way spend time hot summer we...  positive
3  basically there's family little boy (jake) thi...  negative
4  petter mattei's "love time money" visually stu...  positive

# **remove url**

In [89]:
# Function to remove URLs
def remove_urls(text):
    # Regular expression to match URLs
    url_pattern = re.compile(r'https?://\S+|www\.\S+')
    return url_pattern.sub('', text)

# Applying the function to the 'review' column
df['review'] = df['review'].apply(remove_urls)
df.head()

                                              review sentiment
0  one reviewers mentioned watching 1 oz episode ...  positive
1  wonderful little production. the filming techn...  positive
2  thought wonderful way spend time hot summer we...  positive
3  basically there's family little boy (jake) thi...  negative
4  petter mattei's "love time money" visually stu...  positive

# **Handling ChatsWords**

In [90]:
# Here Come ChatWords Which i Get from a Github Repository
# Repository Link : https://github.com/rishabhverma17/sms_slang_translator/blob/master/slang.txt
chat_words = {
    "AFAIK": "As Far As I Know",
    "AFK": "Away From Keyboard",
    "ASAP": "As Soon As Possible",
    "ATK": "At The Keyboard",
    "ATM": "At The Moment",
    "A3": "Anytime, Anywhere, Anyplace",
    "BAK": "Back At Keyboard",
    "BBL": "Be Back Later",
    "BBS": "Be Back Soon",
    "BFN": "Bye For Now",
    "B4N": "Bye For Now",
    "BRB": "Be Right Back",
    "BRT": "Be Right There",
    "BTW": "By The Way",
    "B4": "Before",
    "B4N": "Bye For Now",
     "CU": "See You",
    "CUL8R": "See You Later",
    "CYA": "See You",
    "FAQ": "Frequently Asked Questions",
    "FC": "Fingers Crossed",
    "FWIW": "For What It's Worth",
    "FYI": "For Your Information",
    "GAL": "Get A Life",
    "GG": "Good Game",
    "GN": "Good Night",
    "GMTA": "Great Minds Think Alike",
    "GR8": "Great!",
    "G9": "Genius",
    "IC": "I See",
    "ICQ": "I Seek you (also a chat program)",
    "ILU": "ILU: I Love You",
    "IMHO": "In My Honest/Humble Opinion",
    "IMO": "In My Opinion",
    "IOW": "In Other Words",
    "IRL": "In Real Life",
    "KISS": "Keep It Simple, Stupid",
    "LDR": "Long Distance Relationship",
    "LMAO": "Laugh My A.. Off",
    "LOL": "Laughing Out Loud",
    "LTNS": "Long Time No See",
    "L8R": "Later",
    "MTE": "My Thoughts Exactly",
    "M8": "Mate",
    "NRN": "No Reply Necessary",
    "OIC": "Oh I See",
    "PITA": "Pain In The A..",
    "PRT": "Party",
    "PRW": "Parents Are Watching",
    "QPSA?": "Que Pasa?",
    "ROFL": "Rolling On The Floor Laughing",
    "ROFLOL": "Rolling On The Floor Laughing Out Loud",
    "ROTFLMAO": "Rolling On The Floor Laughing My A.. Off",
    "SK8": "Skate",
        "STATS": "Your sex and age",
    "ASL": "Age, Sex, Location",
    "THX": "Thank You",
    "TTFN": "Ta-Ta For Now!",
    "TTYL": "Talk To You Later",
    "U": "You",
    "U2": "You Too",
    "U4E": "Yours For Ever",
    "WB": "Welcome Back",
    "WTF": "What The F...",
    "WTG": "Way To Go!",
    "WUF": "Where Are You From?",
    "W8": "Wait...",
    "7K": "Sick:-D Laugher",
    "TFW": "That feeling when",
    "MFW": "My face when",
    "MRW": "My reaction when",
    "IFYP": "I feel your pain",
    "TNTL": "Trying not to laugh",
    "JK": "Just kidding",
    "IDC": "I don't care",
    "ILY": "I love you",
    "IMU": "I miss you",
    "ADIH": "Another day in hell",
    "ZZZ": "Sleeping, bored, tired",
    "WYWH": "Wish you were here",
    "TIME": "Tears in my eyes",
    "BAE": "Before anyone else",
    "FIMH": "Forever in my heart",
    "BSAAW": "Big smile and a wink",
    "BWL": "Bursting with laughter",
    "BFF": "Best friends forever",
    "CSL": "Can't stop laughing"
}

In [91]:
# Function
def chat_conversion(text):
    new_text = []
    for i in text.split():
        if i.upper() in chat_words:
            new_text.append(chat_words[i.upper()])
        else:
            new_text.append(i)
    return " ".join(new_text)

# Calling Function 
df['review'] = df['review'].apply(chat_conversion)

# Head
df.head()

                                              review sentiment
0  one reviewers mentioned watching 1 oz episode ...  positive
1  wonderful little production. the filming techn...  positive
2  thought wonderful way spend Tears in my eyes h...  positive
3  basically there's family little boy (jake) thi...  negative
4  petter mattei's "love Tears in my eyes money" ...  positive

# **Word_Tokenization**

In [92]:
# Tokenization 
from nltk.tokenize import word_tokenize

# Apply word_tokenize
df['review_word_token'] = df['review'].apply(word_tokenize)

# Head
df.head()

,review,sentiment,review_word_token
0,one reviewers mentioned watching 1 oz episode ...,positive,"[one, reviewers, mentioned, watching, 1, oz, e..."
1,wonderful little production. the filming techn...,positive,"[wonderful, little, production, ., the, filmin..."
2,thought wonderful way spend Tears in my eyes h...,positive,"[thought, wonderful, way, spend, Tears, in, my..."
3,basically there's family little boy (jake) thi...,negative,"[basically, there, 's, family, little, boy, (,..."
4,"petter mattei's ""love Tears in my eyes money"" ...",positive,"[petter, mattei, 's, ``, love, Tears, in, my, ..."

# **Sentence_Tokenization**

In [93]:
# Tokenization 
from nltk.tokenize import sent_tokenize

# Apply sent_tokenize
df['review_sent_token'] = df['review'].apply(sent_tokenize)

# Head
df.head()

,review,sentiment,review_word_token,review_sent_token
0,one reviewers mentioned watching 1 oz episode ...,positive,"[one, reviewers, mentioned, watching, 1, oz, e...",[one reviewers mentioned watching 1 oz episode...
1,wonderful little production. the filming techn...,positive,"[wonderful, little, production, ., the, filmin...","[wonderful little production., the filming tec..."
2,thought wonderful way spend Tears in my eyes h...,positive,"[thought, wonderful, way, spend, Tears, in, my...",[thought wonderful way spend Tears in my eyes ...
3,basically there's family little boy (jake) thi...,negative,"[basically, there, 's, family, little, boy, (,...",[basically there's family little boy (jake) th...
4,"petter mattei's ""love Tears in my eyes money"" ...",positive,"[petter, mattei, 's, ``, love, Tears, in, my, ...","[petter mattei's ""love Tears in my eyes money""..."

# **Stemming**

In [94]:
# Intlize PorterStemmer
ps = PorterStemmer()

# Apply PorterStemmer
df['review_stemmed'] = df['review'].apply(lambda x: ' '.join([ps.stem(word) for word in x.split()]))

# Head
df.head()

,review,sentiment,review_word_token,review_sent_token,review_stemmed
0,one reviewers mentioned watching 1 oz episode ...,positive,"[one, reviewers, mentioned, watching, 1, oz, e...",[one reviewers mentioned watching 1 oz episode...,one review mention watch 1 oz episod hooked. r...
1,wonderful little production. the filming techn...,positive,"[wonderful, little, production, ., the, filmin...","[wonderful little production., the filming tec...",wonder littl production. the film techniqu una...
2,thought wonderful way spend Tears in my eyes h...,positive,"[thought, wonderful, way, spend, Tears, in, my...",[thought wonderful way spend Tears in my eyes ...,thought wonder way spend tear in my eye hot su...
3,basically there's family little boy (jake) thi...,negative,"[basically, there, 's, family, little, boy, (,...",[basically there's family little boy (jake) th...,basic there' famili littl boy (jake) think the...
4,"petter mattei's ""love Tears in my eyes money"" ...",positive,"[petter, mattei, 's, ``, love, Tears, in, my, ...","[petter mattei's ""love Tears in my eyes money""...","petter mattei' ""love tear in my eye money"" vis..."

# **Lemmatization**

In [95]:
# Download NLTK resources (uncomment the following line if not already downloaded)?
import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to /usr/share/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /usr/share/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /usr/share/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

# **Text Representation**

1. What is Feature Extraction from Text?
Feature extraction from text refers to the process of converting textual data into numerical representations. It's also known as text representation or text vectorization.

2. Why Do We Need It?
In natural language processing (NLP) tasks using machine learning, providing effective features to models is crucial. Text vectorization is a pivotal step in ML-based NLP, facilitating the transformation of text data into a format suitable for modeling.

3. Why Is It Difficult?
While it's straightforward to represent data like pixels in images or audio in numerical form, converting text into meaningful numerical representations poses challenges. Text carries rich semantic meaning, and preserving this meaning during conversion is complex.

5. What Are the Techniques?¶
a. One-Hot Encoding (OHE): Assigning a unique binary value to each word in the vocabulary.

b. Bag of Words (BOW): Representing text as a frequency distribution of words, disregarding grammar and word order.

c. N-Grams: Capturing the co-occurrence of adjacent words by considering sequences of n words.

d. Term Frequency-Inverse Document Frequency (TF-IDF): Weighing the importance of words in a document relative to their frequency across the corpus.

# Some Common Terms
#### a. Corpus: The entire collection of text data, comprising all documents or texts under consideration.
#### b. Vocabulary: The set of unique words present in the corpus.
#### c. Document: Each individual piece of text in the corpus, such as a review, article, or sentence.
#### d. Word: The basic unit of textual data, representing a single element of meaning.

In [96]:
# First of all we made a corpus of All words 
corpus = []

# Run a Loop and Append Reviews in corpus
for i in range(len(df)):
    review = re.sub('[^a-zA-Z]', ' ', df['review_stemmed'][i])
    review = review.split()
    review = ' '.join(review)
    corpus.append(review)

# Len Of Corpus
print(f'The Lenght of the Corpus is : {len(corpus)}')

The Lenght of the Corpus is : 50000

In [97]:
# Total number of words in corpus
# Initialize total_words counter
total_words = 0

# Iterate through each element in the corpus list
for text in corpus:
    # Split the text into words and update the total_words counter
    total_words += len(text.split())

# Print the total number of words
print(f"Total words in Corpus is : {total_words}")

Total words in Corpus is : 6373274

In [98]:
# head
corpus[1]

'wonder littl production the film techniqu unassuming old time bbc fashion give comforting sometim discomforting sens realism entir piece the actor extrem well chosen michael sheen ha got polari voic pat too truli see seamless edit guid refer williams diari entries well worth watch terrificli written perform piece master product one great master comedi life the realism realli come home littl things fantasi guard which rather use tradit dream techniqu remain solid disappears play knowledg senses particularli scene concern orton halliwel set particularli flat halliwell mural decor everi surface terribl well done'

# **Vocabulary**

In [99]:
# Let's find the unique words in the corpus
vocabulary = set()

# Apply vocabulary
for review in corpus:
    # Split the review into words
    words = review.split()
    # Update the vocabulary set with unique words from the review
    vocabulary.update(words)

# Convert the set back to a list if needed
vocabulary = list(vocabulary)

# Lenght of Vocab
print(f'The Lenght of the Vocabulary  is : {len(vocabulary)}')

The Lenght of the Vocabulary  is : 97887

In [100]:
# Head of Vocab
vocabulary[0:20]

['sculpture',
 'parma',
 'druggist',
 'binh',
 'taunter',
 'hedda',
 'palances',
 'mandolin',
 'reading',
 'stripes',
 'tulip',
 'peddler',
 'delinquents',
 'stagecoach',
 'ziggi',
 'handover',
 'ferrando',
 'abutt',
 'uner',
 'robson']

# **one hot encoding text:**
In natural language processing (NLP), one-hot encoding (OHE) is a technique used to represent categorical data, such as words or phrases, in a binary format. Each word in a vocabulary is assigned a unique binary vector, where only one bit is set to 1 (indicating the presence of the word) and the rest are set to 0.

In [101]:
vocabulary_short = vocabulary[0:30000]

# Lenght of Vocab
print(f'The Lenght of the Vocabulary  is : {len(vocabulary_short)}')

The Lenght of the Vocabulary  is : 30000

In [102]:
from tensorflow.keras.preprocessing.text import Tokenizer

# Create a tokenizer object with the desired maximum number of words
tokenizer = Tokenizer(num_words=30000)  # Adjust the value as needed

# Fit tokenizer on vocabulary_short to build the vocabulary
tokenizer.fit_on_texts(vocabulary_short)

# One-hot encode the text data
one_hot_encoded = tokenizer.texts_to_matrix(vocabulary_short, mode='binary')

# Print the one-hot encoded representation
print(one_hot_encoded)

[[0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]

# **Bag of Words BOW**

In summary, this code segment imports the CountVectorizer class, initializes it with a maximum feature limit of 10,000, and then fits it to the lemmatized text data to create a document-term matrix representing the word counts in each document.

In [103]:
# import 
from sklearn.feature_extraction.text import CountVectorizer

# Intilize 
cv = CountVectorizer(max_features=10000) # Adjust the Value as needed 

# Fit on Data 
bow = cv.fit_transform(df['review_stemmed'])

# # Show Vocabulary 
print(f'The lenght of the Vocabulary Generated by Bag of Words is : {len(cv.vocabulary_)}')

The lenght of the Vocabulary Generated by Bag of Words is : 10000

In [104]:
# Enocded Sequence from Data 
bow[0].toarray()

array([[0, 0, 0, ..., 0, 0, 0]])

In [105]:
# Number of times each word has occurred
word_counts = bow.toarray().sum(axis=0)
word_counts

array([212, 620,  76, ..., 136,  68,  61])